name: Add new Bluesky profile
description: Use this form to submit an [bluesky.ms] link to [bluesky.ms](https://bluesky.ms).
title: "New bluesky.ms link"
body:
  - type: markdown
    attributes:
      value: |
        🙏 Thank you for taking the time to submit a new bluesky.ms link to [bluesky.ms](https://bluesky.ms)!
        
        A few notes:
        * It will take a few minutes after you submit for the link to appear at [bluesky.ms](https://bluesky.ms).
        * Avoid submitting links that are not meant for public use.
        * Submit a pull request to make advanced edits such as updating the title or deleting an entry. See [Contributing](https://github.com/merill/aka#contributing) for details.
  - type: input
    id: link
    attributes:
      label: Aka.ms link name
      description: Feel free to omit the aka.ms part of the url. E.g. https://aka.ms/intune → intune
      placeholder: ex. intune
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category (Optional. Select None to auto-select)
      description: The category will allow the link to be grouped with it's product family. To add a new category, edit [this file](https://github.com/merill/aka/edit/main/.github/ISSUE_TEMPLATE/add-link.yaml) and submit a pull request.
      options:
        - ai
        - azure
        - dev
        - data
        - dotnet
        - businessapps
        - general
        - microsoft365
        - security
        - windows
    validations:
      required: false
