name: Add new aka.ms link
description: Use this form to submit an [aka.ms] link to [akaSearch.net](https://akasearch.net).
title: "New aka.ms link"
body:
  - type: markdown
    attributes:
      value: |
        🙏 Thank you for taking the time to submit a new aka.ms link to [akaSearch.net](https://akasearch.net)!
        
        A few notes:
        * It will take a few minutes after you submit for the link to appear at [akaSearch.net](https://akasearch.net).
        * Avoid submitting links that are not meant for public use.
        * Submit a pull request to make advanced edits such as updating the title or deleting an entry. See [Contributing](https://github.com/merill/aka#contributing) for details.
  - type: input
    id: link
    attributes:
      label: Aka.ms link name
      description: Feel free to omit the aka.ms part of the url. E.g. https://aka.ms/intune → intune
      placeholder: ex. intune
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category (Optional. Select None to auto-select)
      description: The category will allow the link to be grouped with it's product family. To add a new category, edit [this file](https://github.com/merill/aka/edit/main/.github/ISSUE_TEMPLATE/add-link.yaml) and submit a pull request.
      options:
        - azure
        - azuread
        - defender
        - dynamics365
        - graph
        - intune
        - kql
        - learn
        - microsoft365
        - powerplatform
        - security
        - windows365
    validations:
      required: false
